apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-website
  namespace: portfolio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - talaatharb.net
        - www.talaatharb.net
      secretName: talaatharb-net-tls
  rules:
    - host: talaatharb.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-website
                port:
                  number: 80
    - host: www.talaatharb.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-website
                port:
                  number: 80
